POST https://localhost:7216/auth/login
Content-Type: application/json

{ "Username" : "xbey", "Password" : "12345678" }

###

GET https://localhost:7216/Doctors
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJhYWZkMjA0Yy0xNGFlLTQ4MTUtOGU5ZS1kYTFlNTlhOWJlY2IiLCJpYXQiOiI1LzI1LzIwMjMgODo1ODoxNCBBTSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ4YmV5IiwiZXhwIjoxNjg1MDA4Njk0LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VGcm9udEVuZCJ9.dZr4TNTSTDcHZFDKzYh6D_2q7RdN37w-mfo_75FqCGxSQOcVdhkDzvxrQyrlUPyrjFGgu4mv5W4Ke_2phcMV2w