POST https://localhost:7216/auth/login
Content-Type: application/json

{ "Username" : "testing", "Password" : "testingson" }

###

GET https://localhost:7216/Doctors
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkODk4MWM1Yi01OWQzLTQxMzgtODY4Yi1kN2I5YzEyMmU5MmIiLCJpYXQiOiI1LzIyLzIwMjMgMTI6NTA6NDEgQU0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdGluZyIsImV4cCI6MTY4NDcyMDI0MSwiaXNzIjoiSldUQXV0aGVudGljYXRpb25TZXJ2ZXIiLCJhdWQiOiJKV1RTZXJ2aWNlRnJvbnRFbmQifQ.Z9lWZd2Ne8LAxfUtq93aZwqn78j5ine7FV1ZISjNvbqVszrUAdF5yLGZhTh0ktf4zEFKUHy_ggC6y-MoERqY8w