name: C/C++ CI

on:
  push:
    branches:
      - IoT_GoogleTestingVs
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio Community 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vs_version: '2022'

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        
    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build ../build
        cd ../build
        ctest --output-on-failure
