name: C/C++ CI

on:
  push:
    branches:
      - IoT_GoogleTestingVs
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: cmake/setup-cmake@v1

      - name: Configure and build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
