name: C/C++ CI

on:
  push:
    branches:
      - IoT_GoogleTestingVs
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Build
        run: |
          mkdir build
          cd IoT/SEP4/Test
          cmake -B /home/runner/work/SEP4/SEP4/IoT/SEP4/Test/build .
          cmake --build /home/runner/work/SEP4/SEP4/IoT/SEP4/Test/build
          --help

      - name: Test
        run: |
          cd IoT/SEP4/Test
          ctest --verbose
